### PR TITLE
rebase Experimental/webgl branch to latest version

### PR DESCRIPTION
**Pull request by Thaina**
As it seem webgl branch was staled and very outdated, I try to bring webgl branch closer to newest version and so I could continued trying to make this library work with webgl

Have various place patching with `NotImplementedException` and some native methods are not really compatible, but currently seem like there was no error. And the windows platform are still pass all the tests

### CODE REVIEW

**Comment by karasusan** [comment]
Thanks for your contribution!
I see that there are some conflicts for this PR, can you confirm?

**Comment by Thaina** [comment]
> Thanks for your contribution! I see that there are some conflicts for this PR, can you confirm?

I am not sure why because it not conflict in my 

Although it might be conflict because I am rebase and fix everything before commit, instead of merge. So it conflict with the current branch because it like I have remade the whole latest commit of that branch

**Comment by karasusan** [comment]
@Thaina
I can't merge it because of the conflict, so I would like to make a new branch instead of this old branch.
What do you think about it?

**Comment by Thaina** [comment]
If this work then I am very fine

**Comment by karasusan** [comment]
Added the branch here
https://github.com/Unity-Technologies/com.unity.webrtc/tree/thaina/experimental/webgl-platform

**Comment by karasusan** [comment]
I am closing this PR because I made the new branch to store these change.

**Pull request closed without merging**
