### PR TITLE
feat: Added support for horizontal flip sourceTexture

### PR DESCRIPTION
**Pull request by MaximKurbanov**
When I added support for "VUZIX M400 SMART GLASSES" to the project, the picture from the glasses was diagonally flipped. So I added the horizontal and diagonal flip.

```
videoStreamTrack = new VideoStreamTrack(webCamTexture, false, true); //Flip horizontaly
sourceRawImage.uvRect = new Rect(1, 1, -1, -1); //Flip diagonally for display
```

### CODE REVIEW

**Comment by karasusan** [comment]
@MaximKurbanov

I couldn't imagine the usage what you want when I designed this constructor. This PR makes sense to me but I want to create a new constructor instead of this.

```
public VideoStreamTrack(Texture texture, Vector2 scale, Vector2 offset) 
```

**Review by MaximKurbanov — COMMENTED** [review]
fix: auto flip vertically when sending and receiving video 
#972 
Added the ability to implement your own CopyTexture for send

**Comment by MaximKurbanov** [comment]
### Old:
```
videoStreamTrack = new VideoStreamTrack(webCamTexture, false, true); //Flip horizontaly
sourceRawImage.uvRect = new Rect(1, 1, -1, -1); //Flip diagonally for display
```
### Now:
```
videoStreamTrack = new VideoStreamTrack(webCamTexture, CopyTextureHelper.DiagonalFlipCopy);
sourceImage.uvRect = new Rect(1, 1, -1, -1); //Flip diagonally for display
```

**Comment by karasusan** [comment]
@MaximKurbanov 
It looks good to me.

**Pull request merged**
