### PR TITLE
added dtls_srtp flag

### PR DESCRIPTION
**Pull request by belveder79**

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=419) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=419) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.webrtc?pullRequest=419) it.</sub>

**Comment by belveder79** [comment]
> [CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=419)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=419) before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.webrtc?pullRequest=419) it.

Trying to sign it always results in being dropped to the "login with github" page, followed by an "Error! Invalid accoung"...

**Comment by karasusan** [comment]
@belveder79 
Hi, may I ask you what reason you want to set this property?
Is it for improving the performance which removing the process of encrypting/decrypting?

**Comment by karasusan** [comment]
CLA bot is broken... sorry for that.

**Comment by belveder79** [comment]
Actually I want to enable it (if it is not by default, and I did not find
an info to that). I’m working on integrating the plugin into some other
system, and enabling is mandatory there. That‘s why...

Kazuki Matsumoto ***@***.***> schrieb am Mo. 7. Juni 2021 um
07:46:

**Comment by karasusan** [comment]
@belveder79 
Oh, I misunderstood. that makes sense. 
It looks like no problem to me.

**Comment by karasusan** [comment]
The value name should be `enableDtlsSrtp` not `enable_dtls_srtp`.

**Pull request closed without merging**
