### PR TITLE
add destruct of audio device and move into worker thread

### PR DESCRIPTION
**Pull request by juju812**
to follow webrtc thread model:

https://groups.google.com/g/discuss-webrtc/c/vCfnjG-wxoc

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=450) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=450) before we can accept your contribution.<br/><hr/>**hejun01** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.webrtc?pullRequest=450) it.</sub>

**Comment by karasusan** [comment]
@juju812 
It looks good to me. I apologize for the inconvenience, but please approve the CLA.

**Comment by juju812** [comment]
@karasusan 

Signed :)

**Review by karasusan — APPROVED** [review]

**Comment by karasusan** [comment]
@juju812 
Thanks!

**Pull request merged**
