### PR TITLE
fixing exception string typo

### PR DESCRIPTION
**Pull request by akermen**

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=392) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=392) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.webrtc?pullRequest=392) it.</sub>

**Review by karasusan — APPROVED** [review]

**Comment by akermen** [comment]
Not sure why, but the Contributor License Agreement step shows the error message at the attached screenshot when I try to sign.
sa

**Comment by karasusan** [comment]
@akermen
How about it right now?

**Comment by akermen** [comment]
@karasusan
Unfortunately same error message is displayed.

**Comment by karasusan** [comment]
@akernen
I am sorry for boring you but your cooperation is so helpful for us.
Could you try to access it once again?

**Comment by akermen** [comment]
Tried but no success even after revoked the app authorization and reauthorized at the github settings.

**Pull request merged**
