### PR TITLE
doc: Added 7zip requirement to Plugin readme

### LINKED ISSUE #466: [BUG] tutorial is missing `choco install 7zip`
**Describe the bug**

To run `BuildScripts~>build_plugin_win.cmd`, the 7zip package is required, but the readme doesn't mention that.

**Expected behavior**

`BuildScripts~>build_plugin_win.cmd` should run fine after following the instructions, but fails with

```
'7z' is not recognized as an internal or external command, operable program or batch file.
```

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: n/a
 - Unity Version: n/a
 - Package version: n/a

**Additional context**
Running `choco install 7zip` in an elevated command prompt fixes the problem

### PR DESCRIPTION
**Pull request by Ziriax**
Should fix #466

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=472) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=472) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.webrtc?pullRequest=472) it.</sub>

**Comment by karasusan** [comment]
@Ziriax 
nice.
Could you sign the CLA?

**Review by karasusan — APPROVED** [review]

**Review by kannan-xiao4 — APPROVED** [review]

**Comment by karasusan** [comment]
@Ziriax
remind

**Comment by Ziriax** [comment]
> @Ziriax
> How is it?

Sorry I didn't get a notification for some reason. Done.

Please note that I made https://github.com/iimachines/webrtc-dotnet-core before this project started; although I'm not a webrtc expert, my old experience might be of value for this project. I hope to make enough free time to contribute, but can't promise anything

**Pull request merged**
