### PR TITLE
Updated installation setup with the GitHub URL

### PR DESCRIPTION
**Pull request by suyashjoshi**

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=585) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=585) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.webrtc?pullRequest=585) it.</sub>

**Comment by karasusan** [comment]
@suyashjoshi 
Hi, do you mean that the installation process was failed when putting `com.unity.webrtc@2.4.0-exp.5` into the inputfield?

**Comment by suyashjoshi** [comment]
Yes, you can try it yourself. Looks like what you pasted in not a Git URL, in my PR it's a valid git URL.

**Comment by karasusan** [comment]
`com.unity.webrtc@2.4.0-exp.5` has not released publicly yet. This markdown file will be published here as a package document when releasing the package. Sorry for your confusing.
https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/install.html

**Comment by karasusan** [comment]
@suyashjoshi
Hi, Can I close this PR? Thanks.

**Comment by suyashjoshi** [comment]
sure up to you buddy

**Pull request closed without merging**
