### PR TITLE
feat: Add x86_64 to the Android libwebrtc build script

### PR DESCRIPTION
**Pull request by lumin-leaper**
This is the first pull request to address the feature requested in issue 802: https://github.com/Unity-Technologies/com.unity.webrtc/issues/802

It adds x86_64 as an additional architecture for the Android variant of libwebrtc. This will build and add the x86_64 binaries while also keeping the existing arm based binaries.

It does not add the new binaries to the plugin. A subsequent pull request is required for that once a new build of libwebrtc has been generated from this script as discussed here: https://github.com/Unity-Technologies/com.unity.webrtc/issues/802#issuecomment-1407546319

Legal stuff: “For clarity, in accordance with Item 1 and “Contribution” as defined in the Agreement under which this software is submitted to the Project, this Contribution includes *only* the contents of the submitted files.  Accordingly, external software referenced by this Contribution, including the Android API, are Not a Contribution.  Thus, one will appreciate that no license, or other, rights are granted by this Contribution to, or in connection with, any such external software.”

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=932) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=932) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.webrtc?pullRequest=932) it.</sub>

**Comment by karasusan** [comment]
Hi, thanks for your contribution!
I am testing this PR, and I built a library in the internal CI system. Can you check the library?
https://drive.google.com/file/d/1T7Ae-__VMY6Ugb1f_t0cuLYNg188K1SZ/view?usp=sharing

**Review by karasusan — APPROVED** [review]

**Comment by lumin-leaper** [comment]
@karasusan , it looks good to me.

**Comment by karasusan** [comment]
@lumin-leaper
Thanks for yor response.
We can put the Android x64 static library for the next update. But I need to take more time to support Android x64 officially.

**Review by kannan-xiao4 — APPROVED** [review]

**Comment by lumin-leaper** [comment]
Thanks @karasusan , does your response imply that these changes will still be merged soon? And it is just the second pull request that might take some more time? Or do I misunderstand?

**Comment by karasusan** [comment]
@lumin-leaper
We are preparing the new version of our package until next week. This PR will be merged after releasing it.

**Comment by lumin-leaper** [comment]
@lumin-leaper , got it. Thank you!

**Pull request merged**
