### PR TITLE
fix: improve metal toolbox integration

### PR DESCRIPTION
**Pull request by aet**
Another change from the past. :) Started as an effort to figure out a leak that showed up in Xcode Instruments at the time, unfortunately can't remember the details anymore.. should have written it into commit message.

- Update macOS build deployment target to 10.12+, all supported Unity versions require 10.12 at least
- Compile Obj-C code with ARC support, all of Unity internal code follows the suit these days (incl. Metal)
- Avoid libyuv CPU conversions on each frame, use CVPixelBuffers to improve integration against WebRTC's RTCVideoEncoderH264

- Missing some custom changes: brute forcing to disable any chance for scaling, degration preference, some RTCVideoEncoderH264 behavior.. the intent was to ensure 1080p60 streaming when upstream code tries to play too nice with codec profile/level parsing.

Untested on M1 macs or iOS, but should be fairly platform agnostic?

### CODE REVIEW

**Comment by karasusan** [comment]
@aet
Wow, this is a big change...
We will take time to the pull request review because now we are preparing to release the next version.

Thanks for your valuable contribution.

**Comment by aet** [comment]
no worries, I figured there's a release coming up! and it surely needs hands-on testing on iOS that I haven't done

**Comment by karasusan** [comment]
@aet
I am reviewing this pull request and I am excited that there is a possibility of improving performance on macOS and iOS. As you said, this implementation can skip YUV conversion on CPU. This should be considered to merge.

But honestly, I am proceeding to refactor the encoding process drastically in the branch below. This work fixes many issues about HWA codec reported from many developers. It is under work in progress.
https://github.com/Unity-Technologies/com.unity.webrtc/compare/feat/encoder-thread-wip

After refactoring, I would be glad to develop the VideoToolbox integration. I will make you wait but I hope you understand.

**Comment by aet** [comment]
@karasusan ah I've seen encoder-thread branch hanging in there for quite some time now, I haven't followed the development of it that much but seems like it really is a way bigger change than I was expecting. :) It seems to touch bunch of areas where I have have local workarounds to improve quality

I'm definitely more interested on improving Nvidia performance and mac stuff is just a local testing improvement for me. I may have some time to help out integrating the videotoolbox changes against the new stuff in progress, but meanwhile hopefully this PR gives enough hints what level of control Metal/RTCVideoEncoderH264 integration needs to avoid CPU pass, so it's easy to apply it into the new abstraction going on at feat/encoder-thread-wip

**Pull request closed without merging**
