### PR TITLE
chore: Upgrade package version 2.2.0-preview

### PR DESCRIPTION
**Pull request by karasusan**

### CODE REVIEW

**Review by kannan-xiao4 — APPROVED** [review]

**Comment by karasusan** [comment]
> doesnt work for me on linux, still dllnotfoundexception claiming on a non-nvidia system some cuda-related libs missing. should software encoding work for me, or did i misunderstood something?
> 
> here is what ldd says:
> linux-vdso.so.1 (0x00007ffd3bf4b000)
> libvulkan.so.1 => /lib64/libvulkan.so.1 (0x00007ff377168000)
> libnvcuvid.so.1 => not found
> libnvidia-encode.so.1 => not found
> libcuda.so.1 => not found
> libc++.so.1 => /lib64/libc++.so.1 (0x00007ff3770a4000)
> libc++abi.so.1 => /lib64/libc++abi.so.1 (0x00007ff37706b000)
> libm.so.6 => /lib64/libm.so.6 (0x00007ff376f23000)
> libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff376f08000)
> libc.so.6 => /lib64/libc.so.6 (0x00007ff376d3c000)
> /lib64/ld-linux-x86-64.so.2 (0x00007ff378723000)
> libdl.so.2 => /lib64/libdl.so.2 (0x00007ff376d35000)
> libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff376d13000)

@subjectdenied
Do you want to use a software encoder with vulkan API?

**Comment by subjectdenied** [comment]
@karasusan yes, vulkan. should i use opengl instead?

**Review by sindharta-tanuwijaya — APPROVED** [review]

**Comment by karasusan** [comment]
> @karasusan yes, vulkan. should i use opengl instead?

@subjectdenied 

The software encoder with OpenGL API is not supported yet.
I am afraid that the software encoder with Vulkan API haven't been tested much...

**Comment by karasusan** [comment]
@subjectdenied 
If possible, would you please post an issue to GitHub?
It is helpful for me.

**Comment by karasusan** [comment]
@subjectdenied 
I created the issue. You can add comments for the detail.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/238

**Pull request merged**
