### PR TITLE
added enableDtlsSrtp flag

### PR DESCRIPTION
**Pull request by belveder79**
closed #417 #418 #419 and renamed flag to enableDtlsSrtp

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=425) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.webrtc?pullRequest=425) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.webrtc?pullRequest=425) it.</sub>

**Comment by karasusan** [comment]
Thanks a lot! @belveder79

**Comment by belveder79** [comment]
the bot is still broken - I can't sign the license agreement - any other way to sign it?

**Comment by karasusan** [comment]
Fixed the CLA issue. Could you try again?

**Comment by belveder79** [comment]
Worked, thx!

**Review by karasusan — APPROVED** [review]

**Review by kannan-xiao4 — APPROVED** [review]

**Pull request merged**
